# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Style - PEP8 (currently pycodestyle)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pycodestyle
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with pycodestyle
      run: |
        # First check for critical issues like syntax errors or undefined names
        pycodestyle . --count --select=E9 --show-source --statistics
        # Check for all PEP8 issues with custom line length and exclusions
        pycodestyle . --count --max-line-length=127 --statistics --exclude=migrations,myenv,mysite,__init__.py
